### PR TITLE
Added new standard for the netherlands

### PR DESCRIPTION
**Pull request by peterurk**
Not sure if I've done this right. Can you double check it?

### CODE REVIEW

**Comment by AbcAeffchen** [comment]
Looks like this pull request fails the tests. I will take a closer look at it.
I didn't implement pain.001.001.03 because it is the oldest version of the standard outdated for about 4 years and I thought no one uses it anymore.

Maybe you can fix your code so your code passes the tests.
I try to take a look at the code during the weekend.

**Comment by peterurk** [comment]
Somehow, my bank requires this format. For the biggest part it's abracadabra to me but this seemed to do the trick for me. If you could check my code that would be great because I am not at all sure if I have done this the right way.

**Comment by AbcAeffchen** [comment]
OK, I will take care about this as soon as possible. 
The problem is, that 001.001.03 is the oldest version with more constrains than the newer versions. So you have to make sure, that there is no data missing. This means you have to go through the documentation and check everything and finally have a file checker of a bank check the generated files.

**Comment by AbcAeffchen** [comment]
I took a quick look at some documentation of the standards.
Maybe I confused something. There is a new standard from this year that is called pain.001.001.03.
I could swear that this version number was already used some years ago, but I couldn't find it. Instead I only found pain.001.001.02.

However, both versions (the very old and the very new) differ from the pain.001.002.03 in more details than only the version number. So I have to go through all the details. The new Version pain.001.001.03 is definitely planed for the next weeks. For now I have to decline this pull request.

Can you please check with your bank, that you really need the new standard and not a old standard? If the old standard is needed I would try to implement this too.

**Comment by peterurk** [comment]
Good day to you alex. Thanks for your qucik response. Our bank requeres the
standard I tried to add in my pull request. I added the xsd files I use to
validate my xml before i upload it to the bank in the tests folder.


Met vriendelijke groet,

Peter Post
Telefoon: (+31) 6 214 708 60
Email: peterurk@gmail.com

2016-10-14 1:53 GMT+02:00 Alex Schickedanz <notifications@github.com>:

**Comment by AbcAeffchen** [comment]
@peterurk Have a look at the current dev-master. I added support for pain.001.001.03 as well as for pain.008.001.02. I hope this works with your bank. If you encounter any problems, please report them in the issues.

**Comment by peterurk** [comment]
'That's great. I'll do a test somewhere this day.

**Comment by AbcAeffchen** [comment]
@peterurk Hi, did you had some time to test it? I'm working on some usability changes and going to release a new version in December, so it would be great if you can test it until then :+1:

**Pull request closed without merging**
